root = "/project_root"
tmp_dir = "tmp"

[build]
bin = "tmp/app"
cmd = "CGO_ENABLED=0 go build -o tmp/app ./cmd/api/main.go"
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = ["doc"]
stop_on_error = true
