version: '3.5'
services:
  app:
    build:
      context: .
      target: dev
    command: air
    ports:
      - '8080:8080'
    environment:
      GIN_MODE: debug
    working_dir: /project_root
    volumes:
      - ./:/project_root/
    depends_on:
      - 'db'

  db:
    image: 'mysql:8.0'
    ports:
      - '33065:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-gin-clean-arch
      MYSQL_USER: go-gin-clean-arch
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - './tmp/mysql:/var/lib/mysql'

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./doc/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml