version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - '.:/go/src'
    depends_on:
      - 'db'
  db:
    image: 'mysql:8.0'
    ports:
      - '33065:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-gin-ddd-ideal
      MYSQL_USER: go-gin-ddd-ideal
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - './tmp/mysql:/var/lib/mysql'
