openapi: 3.1.0

info:
  title: Go API
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

tags:
  - name: Health
    description: ヘルスチェック
  - name: User
    description: ユーザー

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /users:
    $ref: './paths/users.yaml#/users'
  /users/login:
    $ref: './paths/users.yaml#/login'
  /users/refresh-token:
    $ref: './paths/users.yaml#/refresh_token'
  /users/reset-password-request:
    $ref: './paths/users.yaml#/reset_password_request'
  /users/reset-password:
    $ref: './paths/users.yaml#/reset_password'
  /users/me:
    $ref: './paths/users.yaml#/me'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
